# Generated by Django 3.2.9 on 2021-12-29 15:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images/users/%Y/')),
                ('phone', models.CharField(max_length=10)),
                ('registration_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('country', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('birth_date', models.DateField(default=datetime.date(2004, 1, 3))),
                ('gender', models.CharField(default='F', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_no', models.IntegerField()),
                ('university', models.CharField(max_length=64)),
                ('faculty', models.CharField(max_length=64)),
                ('study_level', models.CharField(default='Bachelor', max_length=64)),
                ('study_year', models.IntegerField(default=1)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4)),
                ('accumulated_credits', models.IntegerField(blank=True, default=0)),
                ('outstanding_credits', models.IntegerField(blank=True, default=0)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.person')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=128)),
                ('rank', models.CharField(max_length=128)),
                ('office_address', models.CharField(max_length=128)),
                ('website', models.URLField(blank=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.person')),
            ],
        ),
    ]
