# Generated by Django 3.2.9 on 2021-11-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211108_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/persons/%Y/'),
        ),
    ]
