# Generated by Django 3.2.9 on 2021-11-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
