# Generated by Django 3.2.9 on 2021-11-09 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_person_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default=datetime.date(2003, 11, 15)),
        ),
        migrations.AlterField(
            model_name='student',
            name='accumulated_credits',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='final_grade',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='outstanding_credits',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
