# Generated by Django 3.2.9 on 2021-11-17 20:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_alter_person_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default=datetime.date(2003, 11, 22)),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.person'),
        ),
        migrations.AlterField(
            model_name='student',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.person'),
        ),
    ]
