# Generated by Django 3.2.9 on 2022-01-01 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
