# Generated by Django 3.2.9 on 2021-12-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20211226_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='reply',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
