# Generated by Django 3.2.9 on 2021-12-26 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20211226_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='image',
        ),
    ]
