# Generated by Django 3.2.9 on 2021-12-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20211226_2012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
