# Generated by Django 3.2.9 on 2021-12-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_assignment',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='student_assignment',
            name='task_file',
            field=models.FileField(null=True, upload_to='assignments/%Y/'),
        ),
    ]
