# Generated by Django 3.2.9 on 2021-11-08 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211108_1811'),
        ('courses', '0002_auto_20211108_1811'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='professor_assignment',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='professor_assignment',
            name='professor_id',
        ),
        migrations.RemoveField(
            model_name='student_assignment',
            name='assignment_id',
        ),
        migrations.RemoveField(
            model_name='student_assignment',
            name='student_id',
        ),
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.course'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.student'),
        ),
        migrations.AddField(
            model_name='professor_assignment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.course'),
        ),
        migrations.AddField(
            model_name='professor_assignment',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.professor'),
        ),
        migrations.AddField(
            model_name='student_assignment',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grades.professor_assignment'),
        ),
        migrations.AddField(
            model_name='student_assignment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.student'),
        ),
    ]
