# Generated by Django 3.2.9 on 2021-12-22 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_auto_20211222_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_assignment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.professor_assignment'),
        ),
    ]
