# Generated by Django 3.2.9 on 2021-11-08 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_auto_20211108_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_assignment',
            name='assignment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='grades.professor_assignment'),
        ),
    ]
