# Generated by Django 4.0 on 2021-12-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_alter_grade_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_assignment',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
