# Generated by Django 3.2.9 on 2022-01-01 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_student_assignment_grade'),
        ('grades', '0005_alter_student_assignment_grade'),
    ]

    operations = [
    ]
