# Generated by Django 3.2.9 on 2021-12-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(default='12345678', max_length=8)),
                ('year', models.CharField(max_length=32)),
                ('semester', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('credits_no', models.IntegerField(default=4)),
                ('photo', models.ImageField(blank=True, upload_to='images/courses/%Y/')),
                ('professors', models.ManyToManyField(default=[], related_name='courses', to='users.Professor')),
                ('students', models.ManyToManyField(default=[], related_name='courses', to='users.Student')),
            ],
        ),
    ]
