# Generated by Django 3.2.9 on 2021-11-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_professor_website'),
        ('courses', '0002_auto_20211108_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_course',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student_course',
            name='student',
        ),
        migrations.AddField(
            model_name='course',
            name='professors',
            field=models.ManyToManyField(related_name='instructors', to='users.Professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='coursants', to='users.Student'),
        ),
        migrations.DeleteModel(
            name='Professor_Course',
        ),
        migrations.DeleteModel(
            name='Student_Course',
        ),
    ]
