# Generated by Django 3.2.9 on 2021-11-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20211108_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/courses/%Y/'),
        ),
    ]
