# Generated by Django 3.2.9 on 2021-11-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='key',
            new_name='code',
        ),
    ]
