# Generated by Django 3.2.9 on 2021-11-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_person_birth_date'),
        ('courses', '0007_auto_20211114_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='professors',
            field=models.ManyToManyField(default=[], related_name='instructors', to='users.Professor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(default=[], related_name='coursants', to='users.Student'),
        ),
    ]
