# Generated by Django 3.2.9 on 2021-11-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user1_id',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='user2_id',
            new_name='user2',
        ),
    ]
