# Generated by Django 3.2.9 on 2021-12-21 22:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0012_alter_course_description'),
        ('users', '0018_alter_person_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False, null=True)),
                ('closed', models.BooleanField(default=False, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.course')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invitation_from_user', to='users.person')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invitation_to_user', to='users.person')),
            ],
        ),
    ]
