<<<<<<< HEAD
# Generated by Django 3.2.9 on 2021-12-07 20:52

import datetime
from django.db import migrations, models
=======
# Generated by Django 3.2.9 on 2021-12-29 15:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> origin/raul


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> origin/raul
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('unread', models.BooleanField(default=True)),
<<<<<<< HEAD
=======
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
>>>>>>> origin/raul
            ],
        ),
    ]
